<?php

namespace ContainerMe1wKFz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJsonProductPersisterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\JsonProductPersister' shared autowired service.
     *
     * @return \App\Service\JsonProductPersister
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\JsonProductPersister": argument "$projectDir" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
