<?php

namespace ContainerMe1wKFz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4ODNbXW.App\Controller\ProductController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4ODNbXW.App\\Controller\\ProductController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'jsonPersister' => ['privates', 'App\\Service\\JsonProductPersister', NULL, 'Cannot autowire service "App\\Service\\JsonProductPersister": argument "$projectDir" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'entityManager' => '?',
            'jsonPersister' => 'App\\Service\\JsonProductPersister',
        ]))->withContext('App\\Controller\\ProductController::new()', $container);
    }
}
