# config/services.yaml

parameters:
    project_dir: '%kernel.project_dir%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%project_dir%'

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Service\JsonProductPersister:
        arguments:
            $projectDir: '%project_dir%'
