<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2lI8rvP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2lI8rvP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2lI8rvP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2lI8rvP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2lI8rvP\App_KernelDevDebugContainer([
    'container.build_hash' => '2lI8rvP',
    'container.build_id' => '316485ca',
    'container.build_time' => 1721307804,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2lI8rvP');
