<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDSStdG5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDSStdG5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDSStdG5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDSStdG5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDSStdG5\App_KernelDevDebugContainer([
    'container.build_hash' => 'DSStdG5',
    'container.build_id' => 'cb135339',
    'container.build_time' => 1721394087,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDSStdG5');
